<?php

/* custom routes generated by CRUD */


Route::group(array('prefix' => 'admin/ashok/', 'middleware' => 'SentinelAdmin','as'=>'admin.ashok.'), function () {

Route::get('aaaas', ['as'=> 'aaaas.index', 'uses' => 'Ashok\AaaaController@index']);
Route::post('aaaas', ['as'=> 'aaaas.store', 'uses' => 'Ashok\AaaaController@store']);
Route::get('aaaas/create', ['as'=> 'aaaas.create', 'uses' => 'Ashok\AaaaController@create']);
Route::put('aaaas/{aaaas}', ['as'=> 'aaaas.update', 'uses' => 'Ashok\AaaaController@update']);
Route::patch('aaaas/{aaaas}', ['as'=> 'aaaas.update', 'uses' => 'Ashok\AaaaController@update']);
Route::get('aaaas/{id}/delete', array('as' => 'aaaas.delete', 'uses' => 'Ashok\AaaaController@getDelete'));
Route::get('aaaas/{id}/confirm-delete', array('as' => 'aaaas.confirm-delete', 'uses' => 'Ashok\AaaaController@getModalDelete'));
Route::get('aaaas/{aaaas}', ['as'=> 'aaaas.show', 'uses' => 'Ashok\AaaaController@show']);
Route::get('aaaas/{aaaas}/edit', ['as'=> 'aaaas.edit', 'uses' => 'Ashok\AaaaController@edit']);

});


Route::group(array('prefix' => 'admin/dfgfdg/', 'middleware' => 'SentinelAdmin','as'=>'admin.dfgfdg.'), function () {

Route::get('tertrs', ['as'=> 'tertrs.index', 'uses' => 'Dfgfdg\TertrController@index']);
Route::post('tertrs', ['as'=> 'tertrs.store', 'uses' => 'Dfgfdg\TertrController@store']);
Route::get('tertrs/create', ['as'=> 'tertrs.create', 'uses' => 'Dfgfdg\TertrController@create']);
Route::put('tertrs/{tertrs}', ['as'=> 'tertrs.update', 'uses' => 'Dfgfdg\TertrController@update']);
Route::patch('tertrs/{tertrs}', ['as'=> 'tertrs.update', 'uses' => 'Dfgfdg\TertrController@update']);
Route::get('tertrs/{id}/delete', array('as' => 'tertrs.delete', 'uses' => 'Dfgfdg\TertrController@getDelete'));
Route::get('tertrs/{id}/confirm-delete', array('as' => 'tertrs.confirm-delete', 'uses' => 'Dfgfdg\TertrController@getModalDelete'));
Route::get('tertrs/{tertrs}', ['as'=> 'tertrs.show', 'uses' => 'Dfgfdg\TertrController@show']);
Route::get('tertrs/{tertrs}/edit', ['as'=> 'tertrs.edit', 'uses' => 'Dfgfdg\TertrController@edit']);

});
